-- <autogenerated>
--   This file was generated by dddappp code generator.
--   Any changes made to this file manually will be lost next time the file is regenerated.
-- </autogenerated>


--- Module for Tag
-- The module includes functions for creating new Tag objects, 
-- converting them to and from key arrays for storage or transmission purposes.
--
-- @module tag

local tag = {}

function tag.new(name, color)
    local val = {
        name = name,
        color = color,
    }
    return val
end

function tag.to_key_array(val)
    return {
        val and val.name or nil,
        val and val.color or nil,
    }
end

function tag.from_key_array(key_array)
    return tag.new(
        key_array and key_array[1] or nil,
        key_array and key_array[2] or nil
    )
end

return tag
