-- <autogenerated>
--   This file was generated by dddappp code generator.
--   Any changes made to this file manually will be lost next time the file is regenerated.
-- </autogenerated>


--- Module for TaskId
-- The module includes functions for creating new TaskId objects, 
-- converting them to and from key arrays for storage or transmission purposes.
--
-- @module task_id

local task_id = {}

function task_id.new(id)
    local val = {
        id = id,
    }
    return val
end

function task_id.to_key_array(val)
    return {
        val and val.id or nil,
    }
end

function task_id.from_key_array(key_array)
    return task_id.new(
        key_array and key_array[1] or nil
    )
end

return task_id
